### PR TITLE
Remove velvet module from repo

### PR DESCRIPTION
**Pull request by kellymclaughlin**
New repo for the velvet client lib is [here](https://github.com/basho/velvet)

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
Hrm, made distclean and now I'm getting this during a make:

```
==> rel (generate)
ERROR: generate failed while processing /Users/cmeiklejohn/Repositories/riak_cs/rel: {'EXIT',{{badmatch,{error,"Module stanchion_acl_utils potentially included by two different applications: stanchion and velvet."}},
         [{rebar_reltool,generate,2,
                         [{file,"src/rebar_reltool.erl"},{line,50}]},
          {rebar_core,run_modules,4,[{file,"src/rebar_core.erl"},{line,404}]},
          {rebar_core,execute,5,[{file,"src/rebar_core.erl"},{line,333}]},
          {rebar_core,process_dir0,6,[{file,"src/rebar_core.erl"},{line,195}]},
          {rebar_core,process_each,5,[{file,"src/rebar_core.erl"},{line,266}]},
          {rebar_core,process_dir0,6,[{file,"src/rebar_core.erl"},{line,171}]},
          {rebar_core,process_commands,2,
                      [{file,"src/rebar_core.erl"},{line,60}]},
          {rebar,main,1,[{file,"src/rebar.erl"},{line,56}]}]}}
make: *** [rel] Error 1
```

**Comment by cmeiklejohn** [comment]
As, I assume I need to review this one at the same time: basho/stanchion#34

**Comment by kellymclaughlin** [comment]
Yessir

**Comment by cmeiklejohn** [comment]
:+1:, merge away!

**Pull request merged**
