### PR TITLE
Feature/cuttlefish

### PR DESCRIPTION
**Pull request by kuenishi**
Should be rebased after dependencies updated (#87). And should be followed by riak_cs/riak_test update on configuration files. CC: https://github.com/basho/riak_cs/pull/1020

### CODE REVIEW

**Comment by kuenishi** [comment]
Thanks! I didn't notice your +1 :trollface:

**Comment by kuenishi** [comment]
Actually this wasn't reviewed, as Shino's +1 is for 7b7abd8 #87 and not for this pull request where the branch is from there, not branched from develop. My bad, sorry.

**Comment by shino** [comment]
I will do post-merge review the change included in this PR :sweat_smile:

**Comment by shino** [comment]
Done. Review results are included in #91 .

**Pull request merged**
